In [1]:
import numpy as np

a1 = np.ones((2, 3), int)
print(a1)
# [[1 1 1]
#  [1 1 1]]

a2 = np.full((2, 3), 2)
print(a2)
# [[2 2 2]
#  [2 2 2]]

[[1 1 1]
 [1 1 1]]
[[2 2 2]
 [2 2 2]]


In [17]:
a =np.array([[[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
                      [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
                      [1, 0, 0, 0, 1, 0, 1, 1, 1, 1],
                      [1, 0, 1, 0, 1, 0, 0, 0, 1, 1],
                      [1, 0, 1, 0, 1, 1, 0, 1, 1, 1],
                      [1, 0, 1, 0, 0, 1, 0, 0, 0, 1],
                      [1, 0, 1, 1, 0, 1, 1, 1, 0, 1],
                      [1, 0, 1, 1, 0, 0, 0, 1, 0, 1],     
                      [1, 0, 1, 1, 0, 0, 0, 0, 0, 1],
                      [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]],
                     [[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
                      [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
                      [1, 0, 0, 0, 1, 0, 1, 1, 1, 1],
                      [1, 0, 1, 0, 1, 0, 0, 0, 1, 1],
                      [1, 0, 1, 0, 1, 1, 0, 1, 1, 1],
                      [1, 0, 1, 0, 0, 1, 0, 0, 0, 1],
                      [1, 0, 1, 1, 0, 1, 1, 1, 0, 1],
                      [1, 0, 1, 1, 0, 1, 0, 1, 0, 1],     
                      [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
                      [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]],
                     [[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
                      [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
                      [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
                      [1, 1, 1, 1, 1, 0, 0, 1, 1, 1],
                      [1, 1, 1, 0, 1, 1, 0, 1, 1, 1],
                      [1, 0, 1, 0, 0, 1, 0, 0, 0, 1],
                      [1, 0, 1, 1, 0, 1, 1, 1, 0, 1],
                      [1, 0, 1, 1, 0, 1, 1, 1, 0, 1],     
                      [1, 2, 0, 0, 0, 0, 0, 0, 0, 1],
                      [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]]])

In [19]:
a.shape

(3, 10, 10)

In [2]:
a= np.ones((10,10,1))
np.prod(a.shape)

100

In [3]:
a = np.array([0,0,0])
b = np.array([1,2,3])

In [4]:
total = a
total


array([0, 0, 0])

In [5]:
total +=b
total

array([1, 2, 3])

In [6]:
a=-1111
print(a)

-1111


In [7]:
a

-1111

In [8]:
a = [0,0,0]
b = [1,2,3]

In [9]:
a += b
a

[0, 0, 0, 1, 2, 3]

In [10]:
print(np.concatenate([a1, a2]))

[[1 1 1]
 [1 1 1]
 [2 2 2]
 [2 2 2]]


In [11]:
print(np.concatenate([a1, a2], 0))

[[1 1 1]
 [1 1 1]
 [2 2 2]
 [2 2 2]]


In [12]:
print(np.concatenate([a1, a2], 1))

[[1 1 1 2 2 2]
 [1 1 1 2 2 2]]


In [13]:
import numpy as np

original_image = np.ones((128, 384,3), int)
print(original_image.shape)


part1 = original_image[:, :128, :]
part2 = original_image[:, 128:256, :]
part3 = original_image[:, 256:, :]

list=np.array([part1,part2,part3])
print(part2.shape)
list.shape

(128, 384, 3)
(128, 128, 3)


(3, 128, 128, 3)

In [14]:
b2 = np.full((2, 3,4), 2)
print(b2)

[[[2 2 2 2]
  [2 2 2 2]
  [2 2 2 2]]

 [[2 2 2 2]
  [2 2 2 2]
  [2 2 2 2]]]


In [15]:
b1[:,-1,:]

NameError: name 'b1' is not defined

In [ ]:
c1=np.array([[[1,2,3,4],
              [2,2,3,4],
              [3,2,3,4]],
            [[4,2,3,4],
             [5,2,3,4],
             [6,2,3,4]]])

B1=b1[:,:-1,:]
B1

array([[[1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [ ]:
C1=c1[:,:-1,:]
C1

array([[[1, 2, 3, 4],
        [2, 2, 3, 4]],

       [[4, 2, 3, 4],
        [5, 2, 3, 4]]])

In [ ]:
print(np.concatenate([B1, C1], axis=2))

[[[1 1 1 1 1 2 3 4]
  [1 1 1 1 2 2 3 4]]

 [[1 1 1 1 4 2 3 4]
  [1 1 1 1 5 2 3 4]]]


In [ ]:
c2=np.array([[[1,2,3,4],
              [2,2,3,4],
              [3,2,3,4]],
            [[4,2,3,4],
             [5,2,3,4],
             [6,2,3,4]]])

C2=c1[:,1:,:]
C2

array([[[2, 2, 3, 4],
        [3, 2, 3, 4]],

       [[5, 2, 3, 4],
        [6, 2, 3, 4]]])

In [ ]:
print(np.concatenate([b1, b2], 1))

[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]
  [2 2 2 2]
  [2 2 2 2]
  [2 2 2 2]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]
  [2 2 2 2]
  [2 2 2 2]
  [2 2 2 2]]]


In [ ]:
print(np.concatenate([b1, b2], 2))

[[[1 1 1 1 2 2 2 2]
  [1 1 1 1 2 2 2 2]
  [1 1 1 1 2 2 2 2]]

 [[1 1 1 1 2 2 2 2]
  [1 1 1 1 2 2 2 2]
  [1 1 1 1 2 2 2 2]]]


In [ ]:
z = np.full((1, 299,480), 2)
print(z.shape)


(1, 299, 480)


In [ ]:
from tensorflow.keras import backend as K
zres=K.reshape(z,[-1,15])

In [ ]:
zres.shape

TensorShape([9568, 15])

In [ ]:
z7 = np.full((1, 299,32), 2)
print(z7.shape)

(1, 299, 32)


In [ ]:
zres1=K.reshape(z7,[-1,1])
zres1.shape

TensorShape([9568, 1])

In [ ]:
log_pi=np.full((9568,5),3)

In [ ]:
log_pi1=K.sum(log_pi, axis=1,keepdims=True )

In [ ]:
log_pi1.shape

TensorShape([9568, 1])

In [ ]:
log_pi2=log_pi-log_pi1

In [ ]:
log_pi2.shape

TensorShape([9568, 5])

おそらくtf_lognormalの出力は(9568,5)

In [ ]:
z_loss=K.mean(log_pi1)
z_loss.shape

TensorShape([])

In [ ]:
rew_loss=log_pi2

In [ ]:
rew_loss = K.mean(rew_loss)
rew_loss.shape#おそらく

TensorShape([])

In [ ]:
z1 = np.full((4, 300,480), 2)
print(z1.shape)


(4, 300, 480)


In [ ]:
f1 = np.full((10,1), 3)
f1

array([[3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3]])

In [ ]:
f2= np.full((10,5), 1)
f2

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [ ]:
f1-f2

array([[2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2]])

In [ ]:
import tensorflow as tf
log_pi, mu, log_sigma = tf.split(z1, 3, 1)

In [ ]:
log_pi.shape

TensorShape([4, 100, 480])

In [ ]:
mu.shape

TensorShape([4, 100, 480])

In [ ]:
z_true = np.full((4, 300,32), 2)
print(z_true.shape)

(4, 300, 32)


In [ ]:
flat_z_true = K.reshape(z_true,[-1, 1])
flat_z_true

<tf.Tensor: shape=(38400, 1), dtype=int64, numpy=
array([[2],
       [2],
       [2],
       ...,
       [2],
       [2],
       [2]])>

In [ ]:
n1=np.array([3,2,4,5])

In [ ]:
n1[-1]

5

In [ ]:
m1 = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(m1)
print(m1.shape)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
(4, 3)


In [ ]:
m2 = np.array([[1],[2],[3],[4]])
print(m2)
print(m2.shape)

[[1]
 [2]
 [3]
 [4]]
(4, 1)


In [ ]:
mab=m2-m1
mab

array([[ 0, -1, -2],
       [-2, -3, -4],
       [-4, -5, -6],
       [-6, -7, -8]])

In [ ]:
m1-m2

array([[0, 1, 2],
       [2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [ ]:
o1 = np.full((299, 36),3 )
o1[0].shape

(36,)

In [ ]:
o1[0,:].shape

(36,)

In [ ]:
o2=np.full((1,30),2)
o2

array([[2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2]])

In [ ]:
o2[0].shape

(30,)

In [ ]:
o3=np.full(480,3)
o3rs=np.reshape(o3, [-1, 15])


In [ ]:
o3rs.shape

(32, 15)

In [ ]:
log_pi, mu, log_sigma = tf.split(o3rs, 3, 1)

In [ ]:
mu.shape

TensorShape([32, 5])

In [ ]:
muco=np.copy(mu)
muco.shape

(32, 5)

In [ ]:
muco.size

160

In [ ]:
z_pred=np.full([2,299,480],1)
z_pred.shape

(2, 299, 480)

In [ ]:
z_predrs=K.reshape(z_pred, [-1, 15])
z_predrs.shape

TensorShape([19136, 15])

In [ ]:
log_pi, mu, log_sigma = tf.split(z_predrs, 3, 1)
log_pi.shape

TensorShape([19136, 5])

In [ ]:
np.random.randint(5)

0

In [ ]:
next_z=np.full(32,3)
next_z.shape

(32,)

In [ ]:
zk=np.array([next_z])
zk.shape

(1, 32)

In [ ]:
next_a=np.array([1,1,0])
next_a.shape

(3,)

In [ ]:
next_r=1

In [ ]:
next_zc = np.concatenate([next_z, [1,1,0], [next_r]])
next_zc.shape

(36,)

In [ ]:
next_zc

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 1, 1, 0, 1])

In [ ]:
g1=4
next_zcg1 = np.concatenate([next_z, [g1]])
next_zcg1.shape

(33,)

In [ ]:
h1 = np.array(next_zc).flatten()
h1.shape

(36,)

In [ ]:
h2=np.full(288,8)
hf=np.array(h2).flatten()
w=np.full((288,3),2)
hmat = np.matmul(hf, w)
hmat.shape

(3,)

In [ ]:
t=0
for i in range(10):
    if t%1==0:
        print(i)

0
1
2
3
4
5
6
7
8
9
